enhance video streaming
APCVSRepo/sdl_android pull request #2
Opened 2017-03-29 08:30 UTC by 914802951

enhance video streaming

2017-03-30 07:19 UTC, BrandonHe commented
@914802951 
Could you please add more information for this PR? Here is a good template for your reference.[Example](https://github.com/smartdevicelink/sdl_ios/pull/45)

## Summary
请用中文描述发该PR的原因，分析PR要解决的当前SDL_android proxy存在的瓶颈和问题，罗列描述改进的思路等。
## In Depth
更深入的解释，列出解决方案，支持依据等。

2017-03-30 07:48 UTC, BrandonHe requested changes

2017-03-30 07:48 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        int i = byteCount;
@914802951 
推荐用更加有意义的命名方式代替`i`，`j`等比较晦涩难懂的变量。

2017-03-30 07:48 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +    public PipedInputStream(PipedOutputStream out) throws IOException {
请对所有的函数添加相应的注释说明，可参考下列文档：
[JavaDoc style documentation](http://www.oracle.com/technetwork/articles/java/index-137868.html)

2017-03-30 07:48 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +    synchronized void receive(byte[] bytes, int byteOffset, int byteCount) throws IOException {
请对函数添加相应的注释说明，可参考下列文档：
[JavaDoc style documentation](http://www.oracle.com/technetwork/articles/java/index-137868.html)

2017-03-31 05:48 UTC, 914802951 commented
Proxy中使用到了PipedInputStream、PipedOutputStream两个类进行IO操作，由于写线程是单字节往Buffer里面写入，写入单字节后会唤醒读线程（线程由阻塞态转换成可执行态），然后继续写入下一个字节，当CPU有空闲的时候进行轮询然后执行读线程（线程由可执行态变为执行态），此时可能写线程占有临界资源，导致读线程阻塞（由执行态变为阻塞态），频繁的CPU状态切换会降低CPU运行效率，增大耗电量。另外，读线程在不恰当的时候抢占到临界资源也会降低Proxy传输效率，比如：写线程才写很少字节，读线程就抢到临界资源，导致一块数据分成很多帧发送。
通过重新实现PipedInputStream、PipedOutputStream两个类的方式，以块为单位写入Buffer。

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +    protected int in = -1;
这里需不需要加上注释： in< 0 implies the buffer is empty, in == out implies the buffer is full

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        int totalBytes = byteCount;
或许这里变量命名为： `bytesToTransfer = byteCount;`会更好

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            int copyBytes = 0;
推荐使用变量名：`nextTransferBytes` 或者`nextTransferAmount`

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            System.arraycopy(bytes, byteOffset, this.buffer, this.in, copyBytes);
这里是不是要使用`assert`验证一下 要复制的数组 是不是为空？

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        notifyAll();
这里为什么要调用`notifyAll()`，通知线程退出等待状态吗?

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +     * @return next byte of data
请加上这句：`@return  next byte of data, -1 if the end of the stream is reached`

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        if (!this.connected) {
同时需要判断的条件请采用`if()...else if()`:
`!this.connecte`, 
`closeByReader`, 
`writeSide != null && !writeSide.isAlive() && !closedByWriter && (in < 0)`

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +                return -1;
请添加注释说明

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            if (this.writeSide != null && !this.writeSide.isAlive()) {
请对`&&`两边的条件 分别用`()`

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            if (this.writeSide != null && !this.writeSide.isAlive()) {
```
if ((writeSide != null) && (!writeSide.isAlive()) && (--trials < 0)) {
    throw new IOException("Pipe broken");
}
/* might be a writer waiting */
notifyAll();
```

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        int j = this.buffer[this.out++] & 0xFF;
请不要用`j`这种晦涩难懂的变量命名方式

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        if (bytes == null) {
请用`if()...else if()...`优化你的`if()...if()...`。这样当你判断的某个条件为真时，就会立即停止执行后面的`if()...if()...`

2017-03-31 07:22 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        int i = read();
请不要使用`i`,`j`等这种晦涩难懂的命名方式，比如`ch`

2017-03-31 07:41 UTC, 914802951 commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            System.arraycopy(bytes, byteOffset, this.buffer, this.in, copyBytes);
这个没有必要吧，这个函数是给PipedOutputStream的write()调用的，在write里面做过非空判断了

2017-03-31 07:43 UTC, 914802951 commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        notifyAll();
是的，通知读线程退出等待状态

2017-03-31 08:27 UTC, 914802951 commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        if (bytes == null) {
这里的if()...if()...都是抛出异常，函数直接就返回了，后面的代码不会执行

2017-03-31 09:59 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        if (byteCount == 0) {
这里也可以用`else if()`

2017-03-31 09:59 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +        if (this.in < 0) {
推荐使用`if()...else if()...else if()...else()`这样会提高程序执行效率

2017-03-31 09:59 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedInputStream.java
> +            if (this.writeSide != null && !this.writeSide.isAlive()) {
@914802951 这里还是没有修改

2017-03-31 09:59 UTC, BrandonHe commented on sdl_android_lib/src/com/smartdevicelink/streaming/PipedOutputStream.java
> +        if (this.sink == null) {
这里还是推荐使用`if()...else if()...`

2017-04-02 02:10 UTC, merged